### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by marklit** [antonmks/Alenka#104]
Are you planning on picking a license for this project at some point?

**Comment by marklit** [comment]
Sorry, I was looking for a ``LICENSE`` file in the root directory. I can see ``Licensed under the Apache License, Version 2.0`` at the top of the source files.

**Comment by antonmks** [comment]
It is Apache 2.0 license

On Sat, Oct 22, 2016 at 4:29 PM, Mark Litwintschik <notifications@github.com
