### ISSUE TITLE
Create data files

### ISSUE THREAD

**Issue by ChillarAnand** [antonmks/Alenka#78]
In readme, it is mentioned 

> Create your data files :

Can anyone mention how i can create data files?

Thank you.

**Comment by antonmks** [comment]
Just create a loading script :
For example this script loads the data from file lineitems.tbl using tab as
separator, orderkey is in column1 etc.

A := LOAD 'lineitems.tbl' USING ('|') AS (orderkey{1}:int , partkey{2}:int,
suppkey{3}:int, linenumber{4}:int, qty{5}:int,
price{6}:decimal, discount{7}:decimal, tax{8}:decimal,
returnflag{9}:varchar(1), linestatus{10}:varchar(1), shipdate{11}:int,
commitdate{12}:int, receiptdate{13}:int    );
STORE A INTO 'lineitem' BINARY;

When you have a script and the data, run alenka :
./alenka -l 1000 load_lineitem.sql
-l parameter sets the size of pieces that alenka reads at once : 1000 means
that it will load the data in 1GB pieces.
You can see more sample load scripts at load_tpch.zip file at
https://github.com/antonmks/Alenka

Regards,
Anton

**Comment by ChillarAnand** [comment]
got it. thanks!
