### ISSUE TITLE
Cannot compile with gcc5

### ISSUE THREAD

**Issue by KenjiTakahashi** [antonmks/Alenka#79]
This is what happens when I try to compile with gcc 5.1: https://gist.github.com/KenjiTakahashi/a1b01c016e7565f5e000

Specifying `-ccbin g++-4.8` in nvcc invocation works, so it's something with gcc version.
Don't know if this is actually issue with Alenka, moderngpu or CUDA itself?
Versions:
```sh
λ ~/cuda/Alenka/ master* g++ --version
g++ (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

λ ~/cuda/Alenka/ master* nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
```

**Comment by antonmks** [comment]
It looks like CUDA doesn't support gcc 5.1 yet :
 http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#axzz3ezhE0E00

**Comment by KenjiTakahashi** [comment]
I see, so gotta keep the 4.8 compiler in for now :-).
