### ISSUE TITLE
Hardware spec

### ISSUE THREAD

**Issue by vasu-cherlopalle** [antonmks/Alenka#96]
Can you please provide the minimum hardware required for Alenka?

**Comment by hurdad** [comment]
x86 CPU
Takes 10GB RAM to build.
CUDA enabled Nvidia GPU with compute compatibility 3.0 or greater
- https://developer.nvidia.com/cuda-gpus

**Comment by vasu-cherlopalle** [comment]
Built Alenka on Mac by making couple of changes.
- Makefile : to support compute_30
- cm.cu : to getTotalSystemMemory

Executing alenka is throwing following error. Any thoughts??
![screen shot 2016-05-04 at 9 08 07 am](https://cloud.githubusercontent.com/assets/5298044/15030750/02dbe354-1209-11e6-9ce2-9735bf46eb31.png)

**Comment by hurdad** [comment]
typically we load data like this 
./alenka -v load_part.sql

I have not tried alenka on OSX, just CentOS 7

**Comment by vasu-cherlopalle** [comment]
Made necessary changes to resolve the issue.  The changes are in the repo.
