### ISSUE TITLE
mgpu::cuda_exception_t "Invalid device function" exception

### ISSUE THREAD

**Issue by marklit** [antonmks/Alenka#99]
Hi,

I'm running a Nvidia GTX 1080 on Ubuntu 16.04 64-bit, CUDA 8 and the 367.48 driver. I'm trying to compile Alenka but I'm getting the following error when I run the executable after it's been compiled...

```bash
$ src/alenka
```

```
terminate called after throwing an instance of 'mgpu::cuda_exception_t'
  what():  invalid device function
Aborted (core dumped)
```

The moderngpu library looks to be working so I'm not sure why it's throwing an exception. Below are the steps I took to compile Alenka:

```bash
$ git clone https://github.com/antonmks/Alenka.git ~/Alenka
$ cd ~/Alenka
$ git checkout development
$ git submodule init
$ git submodule update

$ cd deps/moderngpu
$ make
```

I then tested the moderngpu library:

```bash
$ mkdir ~/testing
$ cd ~/testing
$ vi hello.cu
```

```c
#include <moderngpu/transform.hxx>

using namespace mgpu;

int main(int argc, char** argv) {
  // The context encapsulates things like an allocator and a stream.
  // By default it prints device info to the console.
  standard_context_t context;

  // Launch five threads to greet us.
  transform([]MGPU_DEVICE(int index) {
    printf("Hello GPU from thread %d\n", index);
  }, 5, context);

  // Synchronize on the context's stream to send the output to the console.
  context.synchronize();

  return 0;
}
```

```bash
$ nvcc \
    -std=c++11 \
    --expt-extended-lambda \
    -gencode arch=compute_50,code=compute_50 \
    -I ../Alenka/deps/moderngpu/src/ \
    -o hello \
    hello.cu

$ ./hello
```

```
GeForce GTX 1080 : 1835.000 Mhz   (Ordinal 0)
20 SMs enabled. Compute Capability sm_61
FreeMem:   6678MB   TotalMem:   8110MB   64-bit pointers.
Mem Clock: 5005.000 Mhz x 256 bits   (320.3 GB/s)
ECC Disabled


Hello GPU from thread 0
Hello GPU from thread 1
Hello GPU from thread 2
Hello GPU from thread 3
Hello GPU from thread 4
```

I then altered the Makefile to support all levels of compute compatibility listed for Alenka:

```bash
$ cd ~/Alenka
$ vi src/Makefile
```

```make
GENCODE_SM30   := -gencode arch=compute_30,code=sm_30
GENCODE_SM35   := -gencode arch=compute_35,code=sm_35
GENCODE_SM50    := -gencode arch=compute_50,code=sm_50
```

I then ran make:

```
$ make
```

As soon as that was done I ran the Alenka binary and got the exception.

```bash
$ src/alenka
```

```
terminate called after throwing an instance of 'mgpu::cuda_exception_t'
  what():  invalid device function
Aborted (core dumped)
```

I've also tried with just the following uncommented:

```
GENCODE_SM30   := -gencode arch=compute_30,code=sm_30
```

and with just this uncommented:

```
GENCODE_SM50    := -gencode arch=compute_50,code=sm_50
```

But neither of them worked either.

I did try with CUDA 7.5 but came up against malloc-related errors.

Any ideas how I can compile Alenka properly?

Thanks,
Mark

**Comment by antonmks** [comment]
I'll see if I can replicate it, but I do not have 1080. Have you tried to compile it with 
GENCODE_SM61   := -gencode arch=compute_61,code=sm_61
? Seems like your card supports compute model 6.1

**Comment by marklit** [comment]
I'll certainly give that a try and report back with my findings.

**Comment by marklit** [comment]
I've compiled Alenka using the following:

```make
#compute compatibility (https://developer.nvidia.com/cuda-gpus)
# GENCODE_SM30	:= -gencode arch=compute_30,code=sm_30
# GENCODE_SM35	:= -gencode arch=compute_35,code=sm_35
# GENCODE_SM50	:= -gencode arch=compute_50,code=sm_50
GENCODE_SM61	:= -gencode arch=compute_61,code=sm_61
GENCODE_FLAGS	:= $(GENCODE_SM30) $(GENCODE_SM35) $(GENCODE_SM50) $(GENCODE_SM61)
```

And I get the following when I run the binary:

```bash
$ make clean
$ make -j4
$ src/alenka
```

```
$ src/alenka 
GeForce GTX 1080 : 1835.000 Mhz   (Ordinal 0)
20 SMs enabled. Compute Capability sm_61
FreeMem:   6729MB   TotalMem:   8113MB   64-bit pointers.
Mem Clock: 5005.000 Mhz x 256 bits   (320.3 GB/s)
ECC Disabled


Usage : alenka [--QPS-test] | [ [-l load size(MB)] [-v] script.sql ]
```

So it looks like it's working. Thank you very much.

**Comment by antonmks** [comment]
Are you planning to run alenka on taxi rides dataset ?
Please let me know if you need any help.

**Comment by marklit** [comment]
I am and any help would be greatly appreciated.

Feel free to drop me an email at some point, it would be good to chat about your project.

**Comment by antonmks** [comment]
Please don't use development branch, it was a part of a joint project with
another guy. I didn't write it, it is not working.
Use main version, it should work fine.
Looks like your data are not loaded. I tested it with the main branch
version and it worked fine.

On Sun, Oct 16, 2016 at 1:52 PM, Mark Litwintschik <notifications@github.com
